name: hugo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: szxzip.net
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/szxzip.net
            git pull origin main
            rm -rf /var/www/html/*
            podman run --rm \
              -v /root/szxzip.net:/src:Z \
              -w /src \
              ghcr.io/gohugoio/hugo:latest \
              --gc --cleanDestinationDir --logLevel debug
            mv /root/szxzip.net/public/{.,}* /var/www/html/
